find_library(GFLAGS_LIBRARY gflags)
if (NOT GFLAGS_LIBRARY)
    message(FATAL_ERROR "gflags not found")
else ()
    message("gflags found ${GFLAGS_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${GFLAGS_LIBRARY})
endif ()

find_library(PROTOBUF_LIBRARY protobuf)
if (NOT PROTOBUF_LIBRARY)
    message(FATAL_ERROR "protobuf not found")
else ()
    message("protobuf found ${PROTOBUF_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${PROTOBUF_LIBRARY})
endif ()

find_library(GLOG_LIBRARY glog)
if (NOT GLOG_LIBRARY)
    message(FATAL_ERROR "glog not found")
else ()
    message("glog found ${GLOG_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${GLOG_LIBRARY})
endif ()

find_library(HDF5_LIBRARY hdf5)
if (NOT HDF5_LIBRARY)
    message(FATAL_ERROR "hdf5 not found")
else ()
    message("hdf5 found ${HDF5_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${HDF5_LIBRARY})
endif ()

find_library(HDF5_HL_LIBRARY hdf5_hl)
if (NOT HDF5_HL_LIBRARY)
    message(FATAL_ERROR "hdf5_hl not found")
else ()
    message("hdf5_hl found ${HDF5_HL_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${HDF5_HL_LIBRARY})
endif ()

if (NOT APPLE)
    include(caffe/cmake/Modules/FindOpenBLAS.cmake)
    list(APPEND MILES_DEEP_LIBRARIES ${OpenBLAS_LIB})
    set(OPEN_CV_VERSION 2.4)
else ()
    set(OPEN_CV_VERSION 3.4)
endif ()

find_package(OpenCV ${OPEN_CV_VERSION} REQUIRED COMPONENTS core highgui imgproc)
list(APPEND MILES_DEEP_LIBRARIES ${OpenCV_LIBRARIES})

find_package(Boost 1.46 REQUIRED COMPONENTS system thread)
list(APPEND MILES_DEEP_LIBRARIES ${Boost_LIBRARIES})