find_library(GFLAGS_LIBRARY gflags)
if (NOT GFLAGS_LIBRARY)
    message(FATAL_ERROR "gflags not found")
else ()
    message("gflags found ${GFLAGS_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${GFLAGS_LIBRARY})
endif ()

find_library(PROTOBUF_LIBRARY protobuf)
if (NOT PROTOBUF_LIBRARY)
    message(FATAL_ERROR "protobuf not found")
else ()
    message("protobuf found ${PROTOBUF_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${PROTOBUF_LIBRARY})
endif ()

find_library(GLOG_LIBRARY glog)
if (NOT GLOG_LIBRARY)
    message(FATAL_ERROR "glog not found")
else ()
    message("glog found ${GLOG_LIBRARY}")
    list(APPEND MILES_DEEP_LIBRARIES ${GLOG_LIBRARY})
endif ()

find_package(HDF5 COMPONENTS HL REQUIRED)
include_directories(SYSTEM ${HDF5_INCLUDE_DIRS} ${HDF5_HL_INCLUDE_DIR})
list(APPEND MILES_DEEP_LIBRARIES ${HDF5_LIBRARIES} ${HDF5_HL_LIBRARIES})

if (NOT APPLE)
    include(caffe/cmake/Modules/FindOpenBLAS.cmake)
    list(APPEND MILES_DEEP_LIBRARIES ${OpenBLAS_LIB})
    set(OPEN_CV_VERSION 2.4)
else ()
    set(OPEN_CV_VERSION 3.4)
endif ()

find_package(OpenCV ${OPEN_CV_VERSION} REQUIRED COMPONENTS core highgui imgproc)
list(APPEND MILES_DEEP_LIBRARIES ${OpenCV_LIBRARIES})

find_package(Boost 1.46 REQUIRED COMPONENTS system thread)
list(APPEND MILES_DEEP_LIBRARIES ${Boost_LIBRARIES})